name: 🚀 Deploy to Freemius

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Package plugin ZIP
        run: |
          zip -r bricks-flex-addons-${{ github.ref_name }}.zip . \
            -x .git\* node_modules\* tests\* .github\*

      - name: Publish to Freemius
        uses: freemius/deploy-on-freemius-action@v1
        with:
          api_key:    ${{ secrets.FREEMIUS_API_KEY }}
          api_secret: ${{ secrets.FREEMIUS_API_SECRET }}
          product_id: ${{ secrets.FREEMIUS_PRODUCT_ID }}
          zip_path:   bricks-flex-addons-${{ github.ref_name }}.zip
          version:    ${{ github.ref_name }} 